name: deploy-cloud

on:
  push:
    branches:
      - cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy with Docker Compose
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_CLOUD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_CLOUD }}
          SSH_PORT: ${{ secrets.SSH_PORT_CLOUD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_CLOUD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://$REMOTE_USER@$REMOTE_HOST:$SSH_PORT"

          # Export env. Docker swarm is not able to read .env file
          export $(grep -v '^#' .env | xargs)

          docker compose -f .deploy/cloud/docker-compose.yml pull
          docker stack deploy -c .deploy/cloud/docker-compose.yml order_stack
          docker image prune -f  # clean up none image after built
